http.host: '0.0.0.0'
xpack.monitoring.elasticsearch.hosts: ['http://elasticsearch:9200']
xpack.monitoring.enabled: false
config.reload.automatic: true
config.reload.interval: 3s
pipeline.workers: 1
pipeline.batch.size: 125
pipeline.batch.delay: 50
